# Generated by Django 4.1.2 on 2022-10-28 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stagiaire_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AddField(
            model_name='stagiaireinfo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2022-05-05:00:00:00'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stagiaireinfo',
            name='attestation',
            field=models.FileField(max_length=50, upload_to=''),
        ),
        migrations.AlterField(
            model_name='stagiaireinfo',
            name='cv',
            field=models.FileField(max_length=50, upload_to=''),
        ),
        migrations.AlterField(
            model_name='stagiaireinfo',
            name='diplome',
            field=models.FileField(max_length=50, upload_to=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
