# Generated by Django 4.1.2 on 2022-11-04 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stagiaire_app', '0003_user_username_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stagiaireinfo',
            name='is_viewed',
        ),
    ]
