# Generated by Django 4.1.2 on 2022-11-14 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stagiaire_app', '0004_remove_stagiaireinfo_is_viewed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stagiaireinfo',
            name='attestation',
            field=models.FileField(max_length=50, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='stagiaireinfo',
            name='cv',
            field=models.FileField(max_length=50, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='stagiaireinfo',
            name='diplome',
            field=models.FileField(max_length=50, null=True, upload_to=''),
        ),
    ]
