# Generated by Django 4.1.2 on 2022-11-14 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stagiaire_app', '0005_alter_stagiaireinfo_attestation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stagiaireinfo',
            name='attestation',
        ),
    ]
